name: "Continuous Integration"

on:
  pull_request: ~
  push:
    branches:
      - "master"
  schedule:
    - cron: "42 3 * * 1"

jobs:
  phpunit:
    name: "PHP ${{ matrix.php-version }} ${{ matrix.description }} (deps: ${{ matrix.deps }})"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
        deps:
          - "highest"
        description:
          - ''
        phpunit:
          - false
        include:
          - php-version: "8.1"
            deps: "lowest"
          - description: 'PHPUnit 11'
            deps: "highest"
            php-version: '8.3'
            phpunit: "^11"
          - description: 'PHPUnit 12'
            deps: "highest"
            php-version: '8.4'
            phpunit: "^12"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "pcov"
          ini-values: "zend.assertions=1"

      - run: composer require phpunit/phpunit ${{ matrix.phpunit }} --no-update
        if: matrix.phpunit

      - name: "Install dependencies"
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: ${{ matrix.deps }}
          composer-options: "--prefer-dist"

      - name: "Run PHPUnit"
        run: "vendor/bin/phpunit --coverage-clover=coverage.xml"

      - name: "Run PHP-CS-Fixer (E2E test)"
        run: "vendor/bin/php-cs-fixer fix --dry-run --diff"
        if: "${{ matrix.deps != 'lowest' }}"
        env:
          PHP_CS_FIXER_IGNORE_ENV: true
