name: "Continuous Integration"

on:
  pull_request: ~
  push:
    branches:
      - "master"
  schedule:
    - cron: "42 3 * * 1"

jobs:
  phpunit:
    name: "Tests"
    runs-on: "linux"

    strategy:
      matrix:
        php-version:
          - "8.1"
          - "8.2"
          - "8.3"
        deps:
          - "highest"
        composer-options:
          - "--prefer-dist"


    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "pcov"
          ini-values: "zend.assertions=1"

      - name: "Install dependencies"
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: ${{ matrix.deps }}
          composer-options: ${{ matrix.composer-options }}

      - name: "Run PHPUnit"
        run: "vendor/bin/phpunit --coverage-clover=coverage.xml"

      - name: "Run PHP-CS-Fixer (E2E test)"
        run: "vendor/bin/php-cs-fixer fix --dry-run --diff"
        if: "${{ matrix.deps != 'lowest' }}"
        env:
          PHP_CS_FIXER_IGNORE_ENV: true
